on:
  push:
    branches:
      - main

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
      
        - name: Checkout code
          uses: actions/checkout@v2 

        - name: Setup Java JDK
          uses: actions/setup-java@v4.2.1
          with:
            java-version: 17.0.7
            distribution: 'adopt'

        - name: Build project with Maven
          run: mvn -B package -DskipTests --file pom.xml

        - name: Build Docker image
          run: docker build -t my-image:latest .
        
        - name: Save Docker image as tar file
          run: docker save -o my-image.tar my-image:latest

        - name: Transfer Docker image to remote server
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
        
        - name: Load Docker image on remote server
          run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }} << 'ENDSSH'
            docker load -i my-image.tar
            ENDSSH
