on:
  push:
    branches:
      - main

jobs:
  mainpipeline:

    runs-on: windows-latest

    steps:
      - name: Standard Checkout
        uses: actions/checkout@v2
        
      - name: java17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERPASSWORD}}
          
      - name: Build Docker Container
        run: docker run -d --name jwt-conteiner -p 8080:8181 jwt
