on:
  push:
    branches:
      - main

jobs:
  mainpipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Standard Checkout
        uses: actions/checkout@v2
    
      - name: java17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERPASSWORD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with: 
          context: .
          push: true
          tags: |
            eryckavel/jwt:latest
          pull: true
      
      - name: Build Docker Image
        run: docker build -t jwt .

      - name: Build Docker Containe
        run: docker run --name jwt-conteiner -p 8181:8080 jwt:latest
        
            
