on:
  push:
    branches:
      - main

jobs:
  mainpipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Build Docker image
        run: docker build -t jwt:latest .

      - name: Save Docker image as tar file
        run: docker save -o jwt.tar jwt:latest

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERPASSWORD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with: 
          context: .
          push: true
          tags: |
            eryckavel/jwt:latest

      - name: Build Docker Image
        run: docker pull eryckavel/jwt:latest

      - name: Build Docker Containe
        run: docker run -d --name jwt-conteiner -p 8181:8080 jwt:latest
