on:
  push:
    branches:
      - main

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
      
        - name: Checkout code
          uses: actions/checkout@v2 

        - name: Setup Java JDK
          uses: actions/setup-java@v4.2.1
          with:
            java-version: 17.0.7
            distribution: 'adopt'
            
        - name: SSH into remote server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.REMOTE_SERVER_ADDRESS }}
            username: ${{ secrets.REMOTE_SERVER_USERNAME }}
            key: ${{ secrets.ARTIFACT_SSH_KEY }}
            script: |
              docker pull my-container
              docker run -d --restart=unless-stopped my-container
