on:
  push:
    branches:
      - main


jobs:
  mainpipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Standard Checkout
        uses: actions/checkout@v2
        
      - name: java17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERPASSWORD}}

       - name: Build and push Docker image
        env:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERPASSWORD}}
        run: |
          docker buildx build --platform linux/amd64 -t $username/nome_da_imagem:latest .
          docker login -u $username -p $password
          docker push $username/jwt:latest
