on:
  push:
    branches:
      - main

jobs:
  mainpipeline:

    runs-on: ubuntu-latest

    steps:
      - name: Standard Checkout
        uses: actions/checkout@v2
        
      - name: java17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKERUSERNAME}}
          password: ${{secrets.DOCKERPASSWORD}}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with: 
          context: .
          file: .
          push: true
          tags: |
            eryckavel/jwt:v1
            eryckavel/jwt:latest
            
